version: '2.2'
services:
    app:
      build:
        context: .
        dockerfile: ./deploy/Dockerfile
      ports:
        - "5000:5000"
      volumes:
        - ./app:/code
      environment:
        PYTHONUNBUFFERED: 1
        SENTRY_DSN: "https://2dbef5f10803049dbea45348b013dffa@o4505646280343552.ingest.sentry.io/4505646285127680"

    nginx:
      image: nginx:1.19.2
      volumes:
        - ./deploy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - ./deploy/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      depends_on:
        - app
      ports:
        - 8080:80
      logging:
        driver: gelf
        options:
          gelf-address: udp://127.0.0.1:5044
          tag: nginx